"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = __importDefault(require("styled-components"));
var polished_1 = require("polished");
exports.ChevronLeft = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  background-image: url(data:image/svg+xml;base64,", ");\n  background-position: center;\n  background-repeat: no-repeat;\n  background-size: contain;\n  height: ", ";\n  width: ", ";\n"], ["\n  background-image: url(data:image/svg+xml;base64,",
    ");\n  background-position: center;\n  background-repeat: no-repeat;\n  background-size: contain;\n  height: ", ";\n  width: ", ";\n"])), encodeURIComponent('PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA4NiA4NiI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOiNlZmYzZjY7fTwvc3R5bGU+PC9kZWZzPjx0aXRsZT5jaGV2cm9uLWxlZnQ8L3RpdGxlPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTY1LDgwLjA5LDI5LjI5LDQzLDY1LDUuOTFBMy40OCwzLjQ4LDAsMCwwLDY1LDFhMy40MSwzLjQxLDAsMCwwLTQuODIsMGwwLDBMMjEsNDAuNTVhMy40OSwzLjQ5LDAsMCwwLDAsNC45TDYwLjE1LDg1QTMuNDEsMy40MSwwLDAsMCw2NSw4NWwwLDBBMy40OCwzLjQ4LDAsMCwwLDY1LDgwLjA5WiIvPjwvc3ZnPg=='), polished_1.rem(24), polished_1.rem(24));
exports.ChevronRight = styled_components_1.default.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  background-image: url(data:image/svg+xml;base64,", ");\n  background-position: center;\n  background-repeat: no-repeat;\n  background-size: contain;\n  height: ", ";\n  width: ", ";\n"], ["\n  background-image: url(data:image/svg+xml;base64,",
    ");\n  background-position: center;\n  background-repeat: no-repeat;\n  background-size: contain;\n  height: ", ";\n  width: ", ";\n"])), encodeURIComponent('PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA4NiA4NiI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOiNlZmYzZjY7fTwvc3R5bGU+PC9kZWZzPjx0aXRsZT5jaGV2cm9uLXJpZ2h0PC90aXRsZT48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0yMSw1LjkxLDU2LjcxLDQzLDIxLDgwLjA5QTMuNSwzLjUsMCwwLDAsMjEsODVhMy40MSwzLjQxLDAsMCwwLDQuODIsMGwwLDBMNjUsNDUuNDVhMy40OSwzLjQ5LDAsMCwwLDAtNC45TDI1Ljg1LDFBMy40MSwzLjQxLDAsMCwwLDIxLDFsMCwwQTMuNDgsMy40OCwwLDAsMCwyMSw1LjkxWiIvPjwvc3ZnPg=='), polished_1.rem(24), polished_1.rem(24));
exports.Cross = styled_components_1.default.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  background-image: url(data:image/svg+xml;base64,", ");\n  background-position: center;\n  background-repeat: no-repeat;\n  background-size: contain;\n  height: ", ";\n  width: ", ";\n"], ["\n  background-image: url(data:image/svg+xml;base64,",
    ");\n  background-position: center;\n  background-repeat: no-repeat;\n  background-size: contain;\n  height: ", ";\n  width: ", ";\n"])), encodeURIComponent('PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA4NC40NiA4Ni4wMiI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOiNlZmYzZjY7fTwvc3R5bGU+PC9kZWZzPjx0aXRsZT5jcm9zczwvdGl0bGU+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNODMuMjQsODAuMDksNDcuNTQsNDMsODMuMjQsNS45MWEzLjQ5LDMuNDksMCwwLDAsMC00LjksMy40LDMuNCwwLDAsMC00LjgxLDBsMCwwTDQyLjEyLDM3LjY1LDUuODQsMUEzLjQsMy40LDAsMCwwLDEsMUwxLDFBMy40OSwzLjQ5LDAsMCwwLDEsNS45TDM2LjcsNDMsMSw4MC4wOUEzLjQ5LDMuNDksMCwwLDAsMSw4NWEzLjQxLDMuNDEsMCwwLDAsNC44MiwwbDAsMEw0Mi4xMiw0OC4zNSw3OC40LDg1YTMuNCwzLjQsMCwwLDAsNC44MSwwbDAsMGEzLjM0LDMuMzQsMCwwLDAsLjM2LTQuOEEuMzEuMzEsMCwwLDAsODMuMjQsODAuMDlaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDAuMDEpIi8+PC9zdmc+'), polished_1.rem(16), polished_1.rem(16));
var templateObject_1, templateObject_2, templateObject_3;
